export const strings = {
  close: 'Close',
  cancel: 'Cancel',
  save: 'Save',
  edit: 'Edit',
  delete: 'Delete',
  create: 'Create',
  submit: 'Submit',
  loading: 'Loading...',
  view: 'View',
  details: 'Details',
  noData: 'No data available',
  
  home: 'Home',
  reports: 'Reports',
  admin: 'Admin',
  login: 'Login',
  logout: 'Logout',
  
  carReports: 'Car Damage Reports',
  newReport: 'New Report',
  reportDetails: 'Car Report Details',
  carModel: 'Car Model',
  damageType: 'Damage Type',
  description: 'Description',
  photo: 'Photo',
  status: 'Status',
  created: 'Created',
  updated: 'Updated',
  noReports: 'No car reports found',
  submitFirstReport: 'Submit your first damage report to get started',
  viewDetails: 'View Details',
  editReport: 'Edit Report',
  photoAttached: 'Photo attached',
  
  minor: 'Minor',
  moderate: 'Moderate', 
  severe: 'Severe',
  totalLoss: 'Total Loss',
  
  pending: 'Pending',
  approved: 'Approved',
  inProgress: 'In Progress',
  completed: 'Completed',
  rejected: 'Rejected',
  
  photoUpload: 'Photo Upload',
  advancedSearch: 'Advanced Search',
  betaDashboard: 'Beta Dashboard',
  aiAssessment: 'AI Assessment',
  mobileApp: 'Mobile App',
  premiumAnalytics: 'Premium Analytics',
  
  aiDamageAssessment: 'AI Damage Assessment',
  estimatedCost: 'Estimated repair cost',
  confidence: 'Confidence',
  analysisCompleted: 'Analysis completed',
  
  similarCases: 'Similar Cases',
  avgProcessingTime: 'Avg. Processing Time',
  successRate: 'Success Rate',
  riskScore: 'Risk Score',
  premiumFeaturesEnabled: 'Premium features are available for this session',
  advancedReporting: 'Advanced reporting features available',
  
  damageAssessment: 'Damage Assessment',
  severity: 'Severity',
  low: 'Low',
  medium: 'Medium',
  high: 'High',
  critical: 'Critical',
  unknown: 'Unknown',
  
  email: 'Email',
  password: 'Password',
  adminUser: 'Admin User',
  regularUser: 'Regular User',
  signIn: 'Sign in',
  signingIn: 'Signing in...',
  welcomeBack: 'Welcome back',
  signInToDashboard: 'Sign in to continue to your dashboard',
  professionalAssessmentSystem: 'Professional Assessment System',
  streamlineReporting: 'Streamline your vehicle damage reporting with intelligent feature management and comprehensive tracking.',
  securePlatform: 'Secure Platform',
  securePlatformDesc: 'Enterprise security with role-based permissions and encrypted data storage',
  dynamicFeatures: 'Dynamic Features',
  dynamicFeaturesDesc: 'Control feature rollouts and manage releases without code deployment',
  quickAccess: 'Quick Access',
  adminAccount: 'ADMIN ACCOUNT',
  fullAccess: 'Full Access',
  regularUserLabel: 'REGULAR USER',
  standard: 'Standard',
  emailPlaceholder: 'name@company.com',
  passwordPlaceholder: 'Enter your password',
  fillAllFields: 'Please fill in all fields',
  
  enabled: 'Enabled',
  disabled: 'Disabled',
  active: 'Active',
  inactive: 'Inactive',
  
  enterCarModel: 'e.g., Toyota Camry 2020',
  describeDamage: 'Describe the damage in detail...',
  uploadPhoto: 'Upload a photo',
  dragAndDrop: 'or drag and drop',
  photoFormat: 'PNG, JPG, GIF up to 10MB',
  
  reportSubmitted: 'Report submitted successfully',
  reportUpdated: 'Report updated successfully',
  reportDeleted: 'Report deleted successfully',
  featureDisabled: 'This feature is currently disabled',
  loginRequired: 'Please log in to continue',
  adminRequired: 'Admin access required',
  errorLoading: 'Failed to load data',
  
  minorDamage: 'Small scratches, dents',
  moderateDamage: 'Significant damage, repairable',
  severeDamage: 'Major damage, expensive repair',
  totalLossDamage: 'Beyond repair',
  
  featureFlagManagement: 'Feature Flag Management',
  createFeatureFlag: 'Create Feature Flag',
  editFeatureFlag: 'Edit Feature Flag',
  featureFlagCreated: 'Feature flag created successfully',
  featureFlagUpdated: 'Feature flag updated successfully',
  featureFlagDeleted: 'Feature flag deleted successfully',
  noFeatureFlags: 'No feature flags found',
  createFirstFlag: 'Create your first feature flag to get started',
  flagKey: 'Flag Key',
  flagName: 'Flag Name',
  flagDescription: 'Description',
  flagType: 'Type',
  rolloutPercentage: 'Rollout Percentage',
  allowedUsers: 'Allowed Users',
  analytics: 'Analytics',
  viewAnalytics: 'View Analytics',
  totalChecks: 'Total Checks',
  enabledChecks: 'Enabled Checks',
  uniqueUsers: 'Unique Users',
};

